### ISSUE TITLE
ERROR panicked at 'sd_softdevice_enable err SdmIncorrectInterruptConfiguration'

### ISSUE THREAD

**Issue by dzervas** [embassy-rs/nrf-softdevice#194]
I'm trying to at least get softdevice enabled but I stumble upon this panic error

I know that it's relevant to #16 and #18 but I'm not sure how to solve it. I don't use RTIC.

My target is an nrf52840 and the code about the SoftDevice is:

```rust
	info!("Starting SoftDevice BLE shit");

	let sd_config = nrf_softdevice::Config {
		clock: Some(raw::nrf_clock_lf_cfg_t {
			source: raw::NRF_CLOCK_LF_SRC_XTAL as u8,
			rc_ctiv: 0,
			rc_temp_ctiv: 0,
			accuracy: raw::NRF_CLOCK_LF_ACCURACY_20_PPM as u8,
			// rc_ctiv: 16,
			// rc_temp_ctiv: 2,
			// accuracy: raw::NRF_CLOCK_LF_ACCURACY_500_PPM as u8,
		}),
		conn_gap: Some(raw::ble_gap_conn_cfg_t {
			conn_count: 6,
			event_length: 24,
		}),
		conn_gatt: Some(raw::ble_gatt_conn_cfg_t { att_mtu: 256 }),
		gatts_attr_tab_size: Some(raw::ble_gatts_cfg_attr_tab_size_t { attr_tab_size: 32768 }),
		gap_role_count: Some(raw::ble_gap_cfg_role_count_t {
			adv_set_count: 1,
			periph_role_count: 3,
			central_role_count: 3,
			central_sec_count: 0,
			_bitfield_1: raw::ble_gap_cfg_role_count_t::new_bitfield_1(0),
		}),
		gap_device_name: Some(raw::ble_gap_cfg_device_name_t {
			p_value: b"HelloRust" as *const u8 as _,
			current_len: 9,
			max_len: 9,
			write_perm: unsafe { mem::zeroed() },
			_bitfield_1: raw::ble_gap_cfg_device_name_t::new_bitfield_1(raw::BLE_GATTS_VLOC_STACK as u8),
		}),
		..Default::default()
	};

        // Tried that, changed nothing
	//unsafe { cortex_m::interrupt::enable(); }

	let sd = Softdevice::enable(&sd_config);

	spawner.spawn(softdevice_task(sd)).unwrap();

	info!("Starting advertisement");

	let adv_data = &[
		0x02,
		raw::BLE_GAP_AD_TYPE_FLAGS as u8,
		raw::BLE_GAP_ADV_FLAGS_LE_ONLY_GENERAL_DISC_MODE as u8,
		0x03,
		raw::BLE_GAP_AD_TYPE_16BIT_SERVICE_UUID_COMPLETE as u8,
		0x09,
		0x18,
		0x0a,
		raw::BLE_GAP_AD_TYPE_COMPLETE_LOCAL_NAME as u8,
		b'H',
		b'e',
		b'l',
		b'l',
		b'o',
		b'R',
		b'u',
		b's',
		b't',
	];
	#[rustfmt::skip]
	let scan_data = &[
		0x03, raw::BLE_GAP_AD_TYPE_16BIT_SERVICE_UUID_COMPLETE as u8, 0x09, 0x18,
	];

	let mut config = peripheral::Config::default();
	config.interval = 50;
	let adv = peripheral::NonconnectableAdvertisement::ScannableUndirected {
		adv_data,
		scan_data,
	};
	unwrap!(peripheral::advertise(sd, adv, &config).await);
```

I'm almost sure that something's wrong with my features. Here are my deps and features:

```toml
[dependencies]
embassy-executor   = { version = "0.3.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-futures    = "0.1.0"
embassy-sync       = { version = "0.3.0" }
embassy-time       = "0.1.3"
embassy-usb        = { git = "https://github.com/embassy-rs/embassy", tag = "embassy-sync-v0.3.0", optional = true, features = ["defmt", "msos-descriptor"] }
# embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy", tag = "embassy-sync-v0.3.0", optional = true, features = ["defmt"] }

embassy-rp    = { git = "https://github.com/embassy-rs/embassy", optional = true, tag = "embassy-sync-v0.3.0"}
embassy-nrf   = { git = "https://github.com/embassy-rs/embassy", optional = true, tag = "embassy-sync-v0.3.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "time"]}
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy", optional = true, tag = "embassy-sync-v0.3.0"}
# esp-hal = { version = "0.12.0", optional = true }
# TODO: Add esp-wifi and esp-hal

defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3.1", features = ["defmt", "defmt-error", "print-defmt"] }
fixed = "1.24.0"
static_cell = "1.2"

# cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
rand = { version = "0.8.5", default-features = false }
futures = { version = "0.3.28", default-features = false, features = ["async-await"] }

embedded-hal = { version = "0.2.7" }
embedded-hal-async = { version = "1.0.0-rc.1", optional = true }
embedded-hal-bus = { version = "0.1.0-rc.1" }

usbd-hid = "0.6.1"
embedded-alloc = "0.5.0"
usb-device = { version = "0.2.9", features = ["defmt"] }

# TODO: Needs critical-section-impl?
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice", features = ["defmt", "nrf52840", "s140", "ble-central", "ble-peripheral", "ble-l2cap", "ble-gatt-server", "ble-gatt-client", "ble-rssi", "ble-sec", "critical-section-impl" ] }
# nrf-softdevice-s140 = { git = "https://github.com/embassy-rs/nrf-softdevice" }

[features]
default = [
	"nrf",
	"nrf52840",
	"nightly",
]

# Hardware targets
rp = ["dep:embassy-rp"]
nrf = ["dep:embassy-nrf"]
stm32 = ["dep:embassy-stm32"]
nrf52840 = []
nightly = [
	"static_cell/nightly",
	"embassy-usb",
	"embedded-hal-async",
	"embassy-executor/nightly",
	"embassy-nrf/nightly",
	"nrf-softdevice/nightly"
]
```

Shouldn't the interrupts be enabled by default?
